command:
  grafanacli:
    exec: grafana-cli -h
    exit-status: 0
    stderr: [ ]
    timeout: 20000
  grafana-cli-data-migration:
    exec: grafana-cli admin data-migration encrypt-datasource-passwords
    exit-status: 0
    stdout:
      - "All datasources secrets are already encrypted"
    stderr: [ ]
    timeout: 20000    
file:
  /opt/bitnami/grafana/conf/ldap.toml:
    mode: "0644"
    filetype: file
    exists: true
    group: root
  /opt/bitnami/grafana/data:
    filetype: directory
    exists: true
  /opt/bitnami/grafana/data/plugins/grafana-kubernetes-app:
    filetype: directory
    exists: true
  /opt/bitnami/grafana/conf/provisioning:
    filetype: directory
    exists: true
